######################################################################
# Automatically generated by qmake (3.1) Fri May 26 20:08:37 2017
######################################################################

TEMPLATE = app
TARGET = TDDCalculator
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += calculatorcontroller.h calculatorwidget.h

SOURCES += calculatorcontroller.cpp calculatorwidget.cpp main.cpp
